#!/bin/bash
PIDFILE="/home/artweb/apps/artweb_be/tmp/node.pid"

if [ ! -e "$PIDFILE" ]; then
    echo "$PIDFILE missing, maybe Node.js is already stopped?"
    exit 99
fi

PID=$(cat $PIDFILE)

if [ -e "$PIDFILE" ] && (pgrep -u artweb | grep -x -f $PIDFILE &> /dev/null); then
  kill $PID
  sleep 3
fi

if [ -e "$PIDFILE" ] && (pgrep -u artweb | grep -x -f $PIDFILE &> /dev/null); then
  echo "Node.js did not stop, killing it."
  sleep 3
  kill -9 $PID
fi
rm -f $PIDFILE
echo "Stopped."
